serviceMaps:
 serviceName: Works Measurement Book
 mappings:
 - version: 1.0
   name: Measurement Book Create/Update
   description: Create/Update Measurement Book in egw_measurementbook table
   fromTopic: works-measurementbook-create-update
   isTransaction: true
   queryMaps:
    - query: INSERT INTO egw_measurementbook(id, tenantid, mbrefno, contractorcomments, mbdate, mbissueddate, mbabstract, frompageno, topageno, letterofacceptanceestimate, revisionloa, status, islegacymb, mbamount, approveddate, stateid, cancellationreason, cancellationremarks, billnumber, billdate, partRateExists, createdby, createdtime, lastmodifiedby, lastmodifiedtime, deleted) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) on CONFLICT (id,tenantid) DO UPDATE SET mbrefno=EXCLUDED.mbrefno, contractorcomments=EXCLUDED.contractorcomments, mbdate=EXCLUDED.mbdate, mbissueddate=EXCLUDED.mbissueddate, mbabstract=EXCLUDED.mbabstract, frompageno=EXCLUDED.frompageno, topageno=EXCLUDED.topageno, letterofacceptanceestimate=EXCLUDED.letterofacceptanceestimate, revisionloa=EXCLUDED.revisionloa, status=EXCLUDED.status, islegacymb=EXCLUDED.islegacymb, mbamount=EXCLUDED.mbamount, approveddate=EXCLUDED.approveddate, stateid=EXCLUDED.stateid, cancellationreason=EXCLUDED.cancellationreason, cancellationremarks=EXCLUDED.cancellationremarks, billnumber=EXCLUDED.billnumber, billdate=EXCLUDED.billdate, partRateExists=EXCLUDED.partRateExists, lastmodifiedby=EXCLUDED.lastmodifiedby, lastmodifiedtime=EXCLUDED.lastmodifiedtime, deleted=EXCLUDED.deleted;
      basePath: $.measurementBooks.*
      jsonMaps:

       - jsonPath: $.measurementBooks.*.id
       
       - jsonPath: $.measurementBooks.*.tenantId
         
       - jsonPath: $.measurementBooks.*.mbRefNo
         
       - jsonPath: $.measurementBooks.*.contractorComments
       
       - jsonPath: $.measurementBooks.*.mbDate
         dbType: LONG
       
       - jsonPath: $.measurementBooks.*.mbIssuedDate
         dbType: LONG
       
       - jsonPath: $.measurementBooks.*.mbAbstract
       
       - jsonPath: $.measurementBooks.*.fromPageNo
       
       - jsonPath: $.measurementBooks.*.toPageNo
       
       - jsonPath: $.measurementBooks.*.letterOfAcceptanceEstimate.id

       - jsonPath: $.measurementBooks.*.revisionloa

       - jsonPath: $.measurementBooks.*.status.code
       
       - jsonPath: $.measurementBooks.*.isLegacyMB
                 
       - jsonPath: $.measurementBooks.*.mbAmount
                 
       - jsonPath: $.measurementBooks.*.approvedDate
         dbType: LONG
         
       - jsonPath: $.measurementBooks.*.stateId
                  
       - jsonPath: $.measurementBooks.*.cancellationReason
       
       - jsonPath: $.measurementBooks.*.cancellationRemarks

       - jsonPath: $.measurementBooks.*.billnumber

       - jsonPath: $.measurementBooks.*.billdate

       - jsonPath: $.measurementBooks.*.isPartRate
       
       - jsonPath: $.measurementBooks.*.auditDetails.createdBy
       
       - jsonPath: $.measurementBooks.*.auditDetails.createdTime
       
       - jsonPath: $.measurementBooks.*.auditDetails.lastModifiedBy
  
       - jsonPath: $.measurementBooks.*.auditDetails.lastModifiedTime

       - jsonPath: $.measurementBooks.*.deleted
       
    - query: INSERT INTO egw_measurementbook_details(id, tenantid, measurementbook, loaactivity, quantity, rate, remarks, amount, partrate, reducedrate, createdby, createdtime, lastmodifiedby, lastmodifiedtime, deleted) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) on CONFLICT (id,tenantid) DO UPDATE SET measurementbook=EXCLUDED.measurementbook, loaactivity=EXCLUDED.loaactivity, quantity=EXCLUDED.quantity, rate=EXCLUDED.rate, remarks=EXCLUDED.remarks, amount=EXCLUDED.amount, partrate=EXCLUDED.partrate, reducedrate=EXCLUDED.reducedrate, deleted=EXCLUDED.deleted;
      basePath: $.measurementBooks.*.measurementBookDetails.*
      jsonMaps:

       - jsonPath: $.measurementBooks.*.measurementBookDetails.*.id

       - jsonPath: $.measurementBooks.*.measurementBookDetails.*.tenantId
         
       - jsonPath: $.measurementBooks[?({id} in @.measurementBookDetails[*].id)].id
       
       - jsonPath: $.measurementBooks.*.measurementBookDetails.*.loaActivity.id
       
       - jsonPath: $.measurementBooks.*.measurementBookDetails.*.quantity

       - jsonPath: $.measurementBooks.*.measurementBookDetails.*.rate
       
       - jsonPath: $.measurementBooks.*.measurementBookDetails.*.remarks

       - jsonPath: $.measurementBooks.*.measurementBookDetails.*.amount

       - jsonPath: $.measurementBooks.*.measurementBookDetails.*.partrate

       - jsonPath: $.measurementBooks.*.measurementBookDetails.*.reducedrate
       
       - jsonPath: $.measurementBooks.*.measurementBookDetails.*.auditDetails.createdBy
       
       - jsonPath: $.measurementBooks.*.measurementBookDetails.*.auditDetails.createdTime
       
       - jsonPath: $.measurementBooks.*.measurementBookDetails.*.auditDetails.lastModifiedBy
       
       - jsonPath: $.measurementBooks.*.measurementBookDetails.*.auditDetails.lastModifiedTime

       - jsonPath: $.measurementBooks.*.measurementBookDetails.*.deleted

    - query: INSERT INTO egw_mb_measurementsheet(id, tenantid, remarks, "number", length, width, depthorheight, quantity, measurementbookdetail, loameasurementsheet, createdby, createdtime, lastmodifiedby, lastmodifiedtime, deleted, multiplier) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) on CONFLICT (id,tenantid) DO UPDATE SET remarks=EXCLUDED.remarks, "number"=EXCLUDED."number", length=EXCLUDED.length, width=EXCLUDED.width, depthorheight=EXCLUDED.depthorheight, quantity=EXCLUDED.quantity, measurementbookdetail= EXCLUDED.measurementbookdetail, loameasurementsheet=EXCLUDED.loameasurementsheet, lastmodifiedby=EXCLUDED.lastmodifiedby, lastmodifiedtime=EXCLUDED.lastmodifiedtime, deleted=EXCLUDED.deleted, multiplier=EXCLUDED.multiplier;
      basePath: $.measurementBooks.*.measurementBookDetails.*.measurementSheets.*
      jsonMaps:

       - jsonPath: $.measurementBooks.*.measurementBookDetails.*.measurementSheets.*.id

       - jsonPath: $.measurementBooks.*.measurementBookDetails.*.measurementSheets.*.tenantId
       
       - jsonPath: $.measurementBooks.*.measurementBookDetails.*.measurementSheets.*.remarks
       
       - jsonPath: $.measurementBooks.*.measurementBookDetails.*.measurementSheets.*.number

       - jsonPath: $.measurementBooks.*.measurementBookDetails.*.measurementSheets.*.length
       
       - jsonPath: $.measurementBooks.*.measurementBookDetails.*.measurementSheets.*.width

       - jsonPath: $.measurementBooks.*.measurementBookDetails.*.measurementSheets.*.depthorheight

       - jsonPath: $.measurementBooks.*.measurementBookDetails.*.measurementSheets.*.quantity

       - jsonPath: $.measurementBooks.*.measurementBookDetails[?({id} in @.measurementSheets[*].id)].id

       - jsonPath: $.measurementBooks.*.measurementBookDetails.*.measurementSheets.*.loaMeasurementSheet.id

       - jsonPath: $.measurementBooks.*.measurementBookDetails.*.measurementSheets.*.auditDetails.createdBy
       
       - jsonPath: $.measurementBooks.*.measurementBookDetails.*.measurementSheets.*.auditDetails.createdTime
       
       - jsonPath: $.measurementBooks.*.measurementBookDetails.*.measurementSheets.*.auditDetails.lastModifiedBy
       
       - jsonPath: $.measurementBooks.*.measurementBookDetails.*.measurementSheets.*.auditDetails.lastModifiedTime

       - jsonPath: $.measurementBooks.*.measurementBookDetails.*.measurementSheets.*.deleted

       - jsonPath: $.measurementBooks.*.measurementBookDetails.*.measurementSheets.*.multiplier

    - query: INSERT INTO egw_documentdetail(id, tenantid, objectid, objecttype, documenttype, filestore, latitude, longitude, description, dateofcapture, workprogress, createdby, createdtime, lastmodifiedby, lastmodifiedtime, deleted) VALUES  (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) on CONFLICT (id,tenantid) DO UPDATE SET filestore=EXCLUDED.filestore, documenttype= EXCLUDED.documenttype, latitude=EXCLUDED.latitude, longitude=EXCLUDED.longitude, description=EXCLUDED.description, dateofcapture=EXCLUDED.dateofcapture, workprogress=EXCLUDED.workprogress, lastmodifiedtime=EXCLUDED.lastmodifiedtime, lastmodifiedby=EXCLUDED.lastmodifiedby, deleted=EXCLUDED.deleted;

      basePath: $.measurementBooks.*.documentDetails.*
      jsonMaps:

       - jsonPath: $.measurementBooks.*.documentDetails.*.id
         
       - jsonPath: $.measurementBooks.*.documentDetails.*.tenantId
         
       - jsonPath: $.measurementBooks.*.documentDetails.*.objectId
       
       - jsonPath: $.measurementBooks.*.documentDetails.*.objectType
       
       - jsonPath: $.measurementBooks.*.documentDetails.*.documentType

       - jsonPath: $.measurementBooks.*.documentDetails.*.fileStore

       - jsonPath: $.measurementBooks.*.documentDetails.*.latitude

       - jsonPath: $.measurementBooks.*.documentDetails.*.longitude

       - jsonPath: $.measurementBooks.*.documentDetails.*.description

       - jsonPath: $.measurementBooks.*.documentDetails.*.dateOfCapture

       - jsonPath: $.measurementBooks.*.documentDetails.*.workProgress
       
       - jsonPath: $.measurementBooks.*.assetDetails.*.auditDetails.createdBy
       
       - jsonPath: $.measurementBooks.*.assetDetails.*.auditDetails.createdTime

       - jsonPath: $.measurementBooks.*.documentDetails.*.auditDetails.lastModifiedBy

       - jsonPath: $.measurementBooks.*.documentDetails.*.auditDetails.lastModifiedTime

       - jsonPath: $.measurementBooks.*.documentDetails.*.deleted
       
 - version: 1.0
   name: Contractor Bill Create/Update
   description: Create/Update Contractor Bill in egw_contractorbill table
   fromTopic: works-contractorbill-create-update
   isTransaction: true
   queryMaps:
    - query: INSERT INTO egw_contractorbill(id, billsequencenumber, approveddate, approvedby, cancellationreason, cancellationremarks, letterofacceptanceestimate, stateid, tenantid, createdby, createdtime, lastmodifiedby, lastmodifiedtime, deleted, spillover, workcompletiondate,billNumber,contractorBillAmount) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,?,?,?,?,?) on CONFLICT (id,tenantid) DO UPDATE SET billsequencenumber=EXCLUDED.billsequencenumber, approveddate=EXCLUDED.approveddate, approvedby=EXCLUDED.approvedby, cancellationreason=EXCLUDED.cancellationreason, cancellationremarks=EXCLUDED.cancellationremarks, letterofacceptanceestimate=EXCLUDED.letterofacceptanceestimate, stateid=EXCLUDED.stateid, lastmodifiedby=EXCLUDED.lastmodifiedby, lastmodifiedtime=EXCLUDED.lastmodifiedtime, deleted=EXCLUDED.deleted, spillover=EXCLUDED.spillover, workcompletiondate=EXCLUDED.workcompletiondate, billNumber=EXCLUDED.billNumber, contractorBillAmount=EXCLUDED.contractorBillAmount;
      basePath: $.contractorBills.*
      jsonMaps:

       - jsonPath: $.contractorBills.*.id
       
       - jsonPath: $.contractorBills.*.billSequenceNumber
         
       - jsonPath: $.contractorBills.*.approvedDate
         dbType: LONG
         
       - jsonPath: $.contractorBills.*.approvedBy.userName
       
       - jsonPath: $.contractorBills.*.cancellationReason
       
       - jsonPath: $.contractorBills.*.cancellationRemarks
       
       - jsonPath: $.contractorBills.*.letterOfAcceptanceEstimate.id
       
       - jsonPath: $.contractorBills.*.stateId
       
       - jsonPath: $.contractorBills.*.tenantId
       
       - jsonPath: $.contractorBills.*.auditDetails.createdBy
       
       - jsonPath: $.contractorBills.*.auditDetails.createdTime
       
       - jsonPath: $.contractorBills.*.auditDetails.lastModifiedBy
  
       - jsonPath: $.contractorBills.*.auditDetails.lastModifiedTime 
       
       - jsonPath: $.contractorBills.*.deleted 
       
       - jsonPath: $.contractorBills.*.spillOver 

       - jsonPath: $.contractorBills.*.workCompletionDate

       - jsonPath: $.contractorBills.*.billNumber

       - jsonPath: $.contractorBills.*.contractorBillAmount
       
    - query: INSERT INTO egw_contractorbill_assets(id, tenantid, asset, chartofaccounts, description, amount, contractorbill, createdby, createdtime, lastmodifiedby, lastmodifiedtime, deleted) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) on CONFLICT (id,tenantid) DO UPDATE SET asset=EXCLUDED.asset, chartofaccounts=EXCLUDED.chartofaccounts, description=EXCLUDED.description, amount=EXCLUDED.amount, contractorbill=EXCLUDED.contractorbill, lastmodifiedby=EXCLUDED.lastmodifiedby, 
       lastmodifiedtime=EXCLUDED.lastmodifiedtime, deleted=EXCLUDED.deleted;
      basePath: $.contractorBills.*.assets.*
      jsonMaps:

       - jsonPath: $.contractorBills.*.assets.*.id
       
       - jsonPath: $.contractorBills.*.assets.*.tenantId
         
       - jsonPath: $.contractorBills.*.assets.*.asset.code
         
       - jsonPath: $.contractorBills.*.assets.*.chartOfAccounts.glcode
       
       - jsonPath: $.contractorBills.*.assets.*.description
       
       - jsonPath: $.contractorBills.*.assets.*.amount
       
       - jsonPath: $.contractorBills[?({id} in @.assets[*].id)].id
       
       - jsonPath: $.contractorBills.*.assets.*.auditDetails.createdBy
       
       - jsonPath: $.contractorBills.*.assets.*.auditDetails.createdTime
       
       - jsonPath: $.contractorBills.*.assets.*.auditDetails.lastModifiedBy
  
       - jsonPath: $.contractorBills.*.assets.*.auditDetails.lastModifiedTime       
       
       - jsonPath: $.contractorBills.*.assets.*.deleted
       
    - query: INSERT INTO egw_contractorbill_mb(id, tenantid, measurementbook, contractorbill, createdby, createdtime, lastmodifiedby, lastmodifiedtime, deleted) VALUES (?, ?, ?, ?, ?, ?, ?,?,?) on CONFLICT (id,tenantid) DO UPDATE SET measurementbook=EXCLUDED.measurementbook, contractorbill=EXCLUDED.contractorbill, lastmodifiedby=EXCLUDED.lastmodifiedby, lastmodifiedtime=EXCLUDED.lastmodifiedtime, deleted=EXCLUDED.deleted;
      basePath: $.contractorBills.*.mbForContractorBill.*
      jsonMaps:

       - jsonPath: $.contractorBills.*.mbForContractorBill.*.id
       
       - jsonPath: $.contractorBills.*.mbForContractorBill.*.tenantId
         
       - jsonPath: $.contractorBills.*.mbForContractorBill.*.measurementBook.id
         
       - jsonPath: $.contractorBills.*.mbForContractorBill.*.contractorBill
       
       - jsonPath: $.contractorBills.*.mbForContractorBill.*.auditDetails.createdBy
       
       - jsonPath: $.contractorBills.*.mbForContractorBill.*.auditDetails.createdTime
       
       - jsonPath: $.contractorBills.*.mbForContractorBill.*.auditDetails.lastModifiedBy

       - jsonPath: $.contractorBills.*.mbForContractorBill.*.auditDetails.lastModifiedTime 
  
       - jsonPath: $.contractorBills.*.mbForContractorBill.*.deleted   
       
 - version: 1.0
   name: Measurement Book Create/Update
   description: Back update Measurement Book for bill status
   fromTopic: works-measurementbook-backupdate-for-billstatus
   isTransaction: true
   queryMaps:
    - query: update egw_measurementbook set billExists=? where id=? and tenantId=?;;
      basePath: $.measurementBooks.*
      jsonMaps:

       - jsonPath: $.measurementBooks.*.billExists

       - jsonPath: $.measurementBooks.*.id
       
       - jsonPath: $.measurementBooks.*.tenantId
